# Generated by Django 4.0.5 on 2022-06-20 08:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('thumbnail', models.ImageField(upload_to='static/', verbose_name='썸네일')),
                ('introduction', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('activity_start_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 20, 17, 47, 44, 197350), verbose_name='노출시작일')),
                ('activity_end_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 23, 17, 47, 44, 197350), verbose_name='노출종료일')),
                ('is_activity', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('thumbnail', models.ImageField(upload_to='static/', verbose_name='썸네일')),
                ('introduction', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('activity_start_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 20, 17, 47, 44, 198348), verbose_name='노출시작일')),
                ('activity_end_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 23, 17, 47, 44, 198348), verbose_name='노출종료일')),
                ('is_activity', models.BooleanField(default=True)),
                ('write', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='product.product')),
                ('write', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
