# Generated by Django 4.0.5 on 2022-06-20 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='write',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='write',
            new_name='writer',
        ),
        migrations.AlterField(
            model_name='event',
            name='activity_end_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 23, 19, 53, 50, 154701), verbose_name='노출종료일'),
        ),
        migrations.AlterField(
            model_name='event',
            name='activity_start_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 20, 19, 53, 50, 154701), verbose_name='노출시작일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='activity_end_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 23, 19, 53, 50, 154701), verbose_name='노출종료일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='activity_start_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 20, 19, 53, 50, 154701), verbose_name='노출시작일'),
        ),
    ]
