# Generated by Django 4.0.5 on 2022-06-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리이름')),
                ('introduction', models.TextField(verbose_name='소개')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50, verbose_name='작성자')),
                ('title', models.CharField(max_length=200, verbose_name='글제목')),
                ('article', models.TextField(verbose_name='글내용')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
        ),
    ]
